services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: iot_butler
      POSTGRES_PASSWORD: "_tPZY-tXALsnn-jyvlP6JaNIGH9mHKlj"
    volumes:
      - iot_butler_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "WbsqVT2b4x6nPNYTe_7DrtOg80uMZJ3N"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: iot_butler_test
      POSTGRES_PASSWORD: "X8x0rsvoxl1Ry_byaRGJ12ILU6FNuXQS"
    volumes:
      - iot_butler_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "Lg9BQxkqwNFIcLXWbDLTXK2VpwcOJlUh"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  iot_butler_data:
  iot_butler_test_data:
